version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8080"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    restart: always
